version: '3'

services:
  pokeopener_app:
    env_file:
      - .env
    build:
      context: ./front
    container_name: pokeopener_app
    restart: always
    volumes:
      - .env:/.env
      - ./front/src:/app
    ports:
      - ${FRONT_PORT}:8501
    networks:
      - pokeopener-network

  pokeopener_backend:
    env_file:
      - .env
    build:
      context: ./back
    container_name: pokeopener_back
    restart: always
    volumes:
      - .env:/.env
    ports:
      - ${BACK_PORT}:80
    networks:
      - pokeopener-network
    hostname: pokeopener_back


  pokeopener_database:
    env_file:
      - .env
    image: 'mariadb:latest'
    container_name: pokeopener_database
    restart: always
    environment:
      - MYSQL_USER=${SQL_USER}
      - MYSQL_PASSWORD=${SQL_PWD}
      - MYSQL_DATABASE=${SQL_DB}
      - MYSQL_ROOT_PASSWORD=${SQL_ROOT_PWD}
    volumes:
      - ${SQL_DATA_PATH}:/var/lib/mysql/
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - pokeopener-network
    hostname: pokeopener_database

  pokeopener_phpmyadmin:
    env_file:
      - .env
    image: phpmyadmin/phpmyadmin
    container_name: pokeopener_phpmyadmin
    restart: always
    environment:
      PMA_HOST: pokeopener_database
      PMA_USER: root
      PMA_PASSWORD: ${SQL_ROOT_PWD}
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    networks:
      - pokeopener-network
    ports:
      - ${PMA_PORT}:80

networks:
  pokeopener-network:
    name: pokeopener-network
    driver: bridge