name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r back/requirements.txt
          pip install -r front/requirements.txt

      - name: Run tests
        run: |
          # Add your test commands here
          pytest

  build:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r back/requirements.txt
          pip install -r front/requirements.txt

      - name: Build
        run: |
          # Add your build commands here
          echo "Building the project"

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r back/requirements.txt
          pip install -r front/requirements.txt

      - name: Deploy
        run: |
          # Add your deploy commands here
          echo "Deploying the project"

  release:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r back/requirements.txt
          pip install -r front/requirements.txt

      - name: Build
        run: |
          # Add your build commands here
          echo "Building the project"

      - name: Create Release
        run: |
          # Add your release commands here
          echo "Creating release"