name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io

      - name: Build Docker containers
        run: |
          docker-compose -f docker-compose.yml build

      - name: Start Docker containers
        run: |
          docker-compose -f docker-compose.yml up -d

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r back_test/requirements.txt

      - name: Run tests
        run: |
          # Add your test commands here
          cd back_test & pytest