name: Merge Trunk CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Pokeopener
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Install Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y apt-transport-https ca-certificates curl software-properties-common
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
          sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
          sudo apt-get update
          sudo apt-get install -y docker-ce docker-ce-cli containerd.io docker-compose-plugin docker-compose

      - name: Build Docker image Pokeopener back
        env:
            DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        run: |
          cd back & docker build -t ${{ secrets.DOCKER_USERNAME }}/pokeopener_back:${{ github.sha }} .

      - name: Build Docker image Pokeopener front
        env:
            DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        run: |
          cd front & docker build -t ${{ secrets.DOCKER_USERNAME }}/pokeopener_front:${{ github.sha }} .

      - name: Push Docker image back
        env:
            DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
            DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker push ${{ secrets.DOCKER_USERNAME }}/pokeopener_back:${{ github.sha }}

      - name: Push Docker image front
        env:
            DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
            DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker push ${{ secrets.DOCKER_USERNAME }}/pokeopener_front:${{ github.sha }}